'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DaS_PC_Overlay.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -1|Nothing
        '''1602950|Abyss (Bonfire)
        '''1512962|Anor Londo (Gwyndolin Bonfire)
        '''1512950|Anor Londo (Gwynevere Bonfire)
        '''1512961|Anor Londo (Interior Bonfire)
        '''1512960|Anor Londo (Lady of the Darkling Bonfire)
        '''1322961|Ash Lake (Bonfire #1)
        '''1322960|Ash Lake (Bonfire #2)
        '''1402962|Blighttown (Bridge Bonfire)
        '''1402963|Blighttown (Entrance)
        '''1402961|Blighttown (Swamp Bonfire)
        '''1212950|Chasm of the Abyss (Manus)
        '''1702950|Crystal Cave (Seath)
        '''1602961|Darkroot Basin (Bonfire)
        '''1202961|Darkroot Garden (Bonfire)
        '''1412 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Bonfires() As String
            Get
                Return ResourceManager.GetString("Bonfires", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 14030544|ActionEnd
        '''14023712|AddActionCount
        '''14017664|AddBlockClearBonus
        '''14019616|AddClearCount
        '''14027056|AddCorpseEvent
        '''14024912|AddCurrentVowRankPoint
        '''14042560|AddCustomRoutePoint
        '''14016032|AddDeathCount
        '''14028016|AddEventParts_Ignore
        '''14035040|AddEventSimpleTalk
        '''14034976|AddEventSimpleTalkTimer
        '''14034832|AddFieldInsFilter
        '''14033584|AddGeneEvent
        '''14015312|AddHelpWhiteGhost
        '''14044496|AddHitMaskByBit
        '''14042912|AddInfomationBuffer
        '''14042928|AddInfomationBufferTag
        '''14033776|AddInfomationList
        '''14042864|Add [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FuncLocs() As String
            Get
                Return ResourceManager.GetString("FuncLocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 100|White Sign Soapstone
        '''101|Red Sign Soapstone
        '''102|Red Eye Orb
        '''103|Black Separation Crystal
        '''106|Orange Guidance Soapstone
        '''108|Book of the Guilty
        '''109|Eye of Death
        '''111|Cracked Red Eye Orb
        '''112|Servant Roster
        '''113|Blue Eye Orb
        '''114|Dragon Eye
        '''115|Black Eye Orb (115)
        '''116|Black Eye Orb (116)
        '''117|Darksign
        '''118|Purple Coward&apos;s Crystal
        '''200|Estus Flask (200)
        '''201|Estus Flask (201)
        '''202|Estus Flask+1 (202)
        '''203|Estus Flask+1 (203)
        '''204|Estus Flask+2 (204)
        '''205|Estus Flask+2 (205)
        '''206|Estus Flask+3 (206)        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Goods() As String
            Get
                Return ResourceManager.GetString("Goods", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
